package me.vaqxine.BuycraftAmplification.database;

/*
 * Do NOT edit this file unless you know what you're doing. 
 * All subsystems reference these credentials for running tasks.
 * */

public class Authentication {

    // CosmicPvP
    /*public static String sql_host = "108.61.143.26";
    public static String sql_db = "Buycraft";
    public static String sql_user = "root";
    public static String sql_pass = "C644E488715AB50ACC852C39EF47E71686";
    public static int sql_port = 3306;
    public static final String sql_url = "jdbc:mysql://" + sql_host + ":" + sql_port + "/" + sql_db;*/
    
    // Arkham
    public static String sql_host = "72.8.130.42";
    public static String sql_db = "delayedCommands";
    public static String sql_user = "prison_slave";
    public static String sql_pass = "vf4kv14TqmpAwknlRuLywtfxsJiSzILUU7b1";
    public static int sql_port = 3306;
    public static final String sql_url = "jdbc:mysql://" + sql_host + ":" + sql_port + "/" + sql_db;
	
}
