# BarAnnouncer configuration
#
# Time per announcement change in ticks.
delay: 2
#
# List of announcements
announcements:
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fWelcome back, &e&l{PLAYER}&f.'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fRemember to &c&l/vote &fevery 24 hours!'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fTell your &dfriends &fabout us!'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fTell your &dfriends &fabout us!'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fTell your &dfriends &fabout us!'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fTell your &dfriends &fabout us!'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fTell your &dfriends &fabout us!'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fTell your &dfriends &fabout us!'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fTell your &dfriends &fabout us!'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fTell your &dfriends &fabout us!'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fTell your &dfriends &fabout us!'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fTell your &dfriends &fabout us!'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fTell your &dfriends &fabout us!'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fTell your &dfriends &fabout us!'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&5&lG&b&lT&a&lA&e&lC&6&lr&c&la&5&lf&b&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&b&lG&a&lT&e&lA&6&lC&c&lr&5&la&b&lf&a&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&a&lG&e&lT&6&lA&c&lC&5&lr&b&la&a&lf&e&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&e&lG&6&lT&c&lA&5&lC&b&lr&a&la&e&lf&6&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&6&lG&c&lT&5&lA&b&lC&a&lr&e&la&6&lf&c&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'
- '&c&lG&5&lT&b&lA&a&lC&e&lr&6&la&c&lf&5&lt &4&l> &fAccess the &6&lstore &fwith &c&l/buy'